/* This file is generated, do not edit! */
package unreal;
@:pythonImport("unreal", "AISenseConfig") extern class AISenseConfig extends unreal.Object {
	/**
		(Color):  [Read-Only] Debug Color
	**/
	public var debug_color : unreal.Color;
	/**
		(float):  [Read-Only] specifies age limit after stimuli generated by this sense become forgotten. 0 means "never"
	**/
	public var max_age : Float;
	/**
		(bool):  [Read-Only] determines whether given sense starts in an enabled state
	**/
	public var starts_enabled : Bool;
}