/* This file is generated, do not edit! */
package unreal;
@:pythonImport("unreal", "AudioComponent") extern class AudioComponent extends unreal.SceneComponent {
	/**
		Initialize self.  See help(type(self)) for accurate signature.
	**/
	@:native("__init__")
	public function ___init__(?args:python.VarArgs<Dynamic>, ?kwargs:python.KwArgs<Dynamic>):Dynamic;
	/**
		Initialize self.  See help(type(self)) for accurate signature.
	**/
	public function new(?args:python.VarArgs<Dynamic>, ?kwargs:python.KwArgs<Dynamic>):Void;
	/**
		x.adjust_attenuation(attenuation_settings) -> None
		This function is used to modify the Attenuation Settings on the targeted Audio Component instance. It is worth noting that Attenuation Settings are only passed to new Active Sounds on start, so modified Attenuation data should be set before sound playback.
		
		Args:
		    attenuation_settings (SoundAttenuationSettings):
	**/
	public function adjust_attenuation(attenuation_settings:unreal.SoundAttenuationSettings):Void;
	/**
		x.adjust_volume(adjust_volume_duration, adjust_volume_level, fade_curve=AudioFaderCurve.LINEAR) -> None
		This function allows designers to trigger an adjustment to the sound instance’s playback Volume with options for smoothly applying a curve over time.
		
		Args:
		    adjust_volume_duration (float): The length of time in which to interpolate between the initial volume and the new volume.
		    adjust_volume_level (float): The new volume to set the Audio Component to.
		    fade_curve (AudioFaderCurve): The curve used when interpolating between the old and new volume.
	**/
	public function adjust_volume(adjust_volume_duration:Float, adjust_volume_level:Float, ?fade_curve:unreal.AudioFaderCurve):Void;
	/**
		(bool):  [Read-Write] Overrides spatialization enablement in either the attenuation asset or on this audio component's attenuation settings override.
	**/
	public var allow_spatialization : Bool;
	/**
		(SoundAttenuationSettings):  [Read-Write] If bOverrideSettings is true, the attenuation properties to use for sounds generated by this component
	**/
	public var attenuation_overrides : unreal.SoundAttenuationSettings;
	/**
		(SoundAttenuation):  [Read-Write] If bOverrideSettings is false, the asset to use to determine attenuation properties for sounds generated by this component
	**/
	public var attenuation_settings : unreal.SoundAttenuation;
	/**
		(AttachmentRule):  [Read-Write] Options for how we handle our location when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
		see: bAutoManageAttachment, EAttachmentRule
	**/
	public var auto_attach_location_rule : unreal.AttachmentRule;
	/**
		(SceneComponent):  [Read-Only] Component we automatically attach to when activated, if bAutoManageAttachment is true.
		If null during registration, we assign the existing AttachParent and defer attachment until we activate.
		see: bAutoManageAttachment
	**/
	public var auto_attach_parent : unreal.SceneComponent;
	/**
		(AttachmentRule):  [Read-Write] Options for how we handle our rotation when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
		see: bAutoManageAttachment, EAttachmentRule
	**/
	public var auto_attach_rotation_rule : unreal.AttachmentRule;
	/**
		(AttachmentRule):  [Read-Write] Options for how we handle our scale when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
		see: bAutoManageAttachment, EAttachmentRule
	**/
	public var auto_attach_scale_rule : unreal.AttachmentRule;
	/**
		(Name):  [Read-Write] Socket we automatically attach to on the AutoAttachParent, if bAutoManageAttachment is true.
		see: bAutoManageAttachment
	**/
	public var auto_attach_socket_name : unreal.Name;
	/**
		(bool):  [Read-Only] True if we should automatically attach to AutoAttachParent when Played, and detach from our parent when playback is completed.
		This overrides any current attachment that may be present at the time of activation (deferring initial attachment until activation, if AutoAttachParent is null).
		If enabled, this AudioComponent's WorldLocation will no longer be reliable when not currently playing audio, and any attach children will also be
		detached/attached along with it.
		When enabled, detachment occurs regardless of whether AutoAttachParent is assigned, and the relative transform from the time of activation is restored.
		This also disables attachment on dedicated servers, where we don't actually activate even if bAutoActivate is true.
		see: AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType
	**/
	public var auto_manage_attachment : Bool;
	/**
		(Set(SoundConcurrency)):  [Read-Write] What sound concurrency rules to use for sounds generated by this audio component
	**/
	public var concurrency_set : Dynamic;
	/**
		(bool):  [Read-Write] Whether or not to apply a low-pass filter to the sound that plays in this audio component.
	**/
	public var enable_low_pass_filter : Bool;
	/**
		(int32):  [Read-Write] The attack time in milliseconds for the envelope follower. Delegate callbacks can be registered to get the
		envelope value of sounds played with this audio component. Only used in audio mixer.
	**/
	public var envelope_follower_attack_time : Int;
	/**
		(int32):  [Read-Write] The release time in milliseconds for the envelope follower. Delegate callbacks can be registered to get the
		envelope value of sounds played with this audio component. Only used in audio mixer.
	**/
	public var envelope_follower_release_time : Int;
	/**
		x.fade_in(fade_in_duration, fade_volume_level=1.000000, start_time=0.000000, fade_curve=AudioFaderCurve.LINEAR) -> None
		This function allows designers to call Play on an Audio Component instance while applying a volume curve over time.
		Parameters allow designers to indicate the duration of the fade, the curve shape, and the start time if seeking into the sound.
		
		Args:
		    fade_in_duration (float): How long it should take to reach the FadeVolumeLevel
		    fade_volume_level (float): The percentage of the AudioComponents's calculated volume to fade to
		    start_time (float): 
		    fade_curve (AudioFaderCurve): The curve to use when interpolating between the old and new volume
	**/
	public function fade_in(fade_in_duration:Float, fade_volume_level:Float = 1.000000, start_time:Float = 0.000000, ?fade_curve:unreal.AudioFaderCurve):Void;
	/**
		x.fade_out(fade_out_duration, fade_volume_level, fade_curve=AudioFaderCurve.LINEAR) -> None
		This function allows designers to call a delayed Stop on an Audio Component instance while applying a
		volume curve over time. Parameters allow designers to indicate the duration of the fade and the curve shape.
		
		Args:
		    fade_out_duration (float): how long it should take to reach the FadeVolumeLevel
		    fade_volume_level (float): the percentage of the AudioComponents's calculated volume in which to fade to
		    fade_curve (AudioFaderCurve): The curve to use when interpolating between the old and new volume
	**/
	public function fade_out(fade_out_duration:Float, fade_volume_level:Float, ?fade_curve:unreal.AudioFaderCurve):Void;
	/**
		x.get_attenuation_settings_to_apply() -> SoundAttenuationSettings or None
		Retrieves Attenuation Settings data on the targeted Audio Component. Returns FALSE if no settings were found.
		Because the Attenuation Settings data structure is copied, FALSE returns will return default values.
		
		Returns:
		    SoundAttenuationSettings or None: 
		
		    out_attenuation_settings (SoundAttenuationSettings):
	**/
	public function get_attenuation_settings_to_apply():Dynamic;
	/**
		x.get_cooked_envelope_data() -> float or None
		Retrieves Cooked Envelope Data at the current playback time. If there are multiple
		SoundWaves playing, data is interpolated and averaged across all playing sound waves.
		Returns FALSE if no data was found.
		
		Returns:
		    float or None: 
		
		    out_envelope_data (float):
	**/
	public function get_cooked_envelope_data():Dynamic;
	/**
		x.get_cooked_envelope_data_for_all_playing_sounds() -> Array(SoundWaveEnvelopeDataPerSound) or None
		Retrieves the current-time envelope data of the sounds playing audio component.
		Envelope data is not averaged or interpolated. Instead an array of data with all playing sound waves with cooked data is returned.
		Returns true if there is data and the audio component is playing.
		
		Returns:
		    Array(SoundWaveEnvelopeDataPerSound) or None: 
		
		    out_envelope_data (Array(SoundWaveEnvelopeDataPerSound)):
	**/
	public function get_cooked_envelope_data_for_all_playing_sounds():Array<SoundWaveEnvelopeDataPerSound>;
	/**
		x.get_cooked_fft_data(frequencies_to_get) -> Array(SoundWaveSpectralData) or None
		Retrieves the current-time cooked spectral data of the sounds playing on the audio component.
		Spectral data is averaged and interpolated for all playing sounds on this audio component.
		Returns true if there is data and the audio component is playing.
		
		Args:
		    frequencies_to_get (Array(float)): 
		
		Returns:
		    Array(SoundWaveSpectralData) or None: 
		
		    out_sound_wave_spectral_data (Array(SoundWaveSpectralData)):
	**/
	public function get_cooked_fft_data(frequencies_to_get:Array<Float>):Array<SoundWaveSpectralData>;
	/**
		x.get_cooked_fft_data_for_all_playing_sounds() -> Array(SoundWaveSpectralDataPerSound) or None
		Retrieves the current-time cooked spectral data of the sounds playing audio component.
		Spectral data is not averaged or interpolated. Instead an array of data with all playing sound waves with cooked data is returned.
		Returns true if there is data and the audio component is playing.
		
		Returns:
		    Array(SoundWaveSpectralDataPerSound) or None: 
		
		    out_sound_wave_spectral_data (Array(SoundWaveSpectralDataPerSound)):
	**/
	public function get_cooked_fft_data_for_all_playing_sounds():Array<SoundWaveSpectralDataPerSound>;
	/**
		x.get_play_state() -> AudioComponentPlayState
		Returns the enumerated play states of the audio component.
		
		Returns:
		    AudioComponentPlayState:
	**/
	public function get_play_state():unreal.AudioComponentPlayState;
	/**
		x.has_cooked_amplitude_envelope_data() -> bool
		Queries whether or not the targeted Audio Component instance’s sound has Envelope Data, returns FALSE if none found.
		
		Returns:
		    bool:
	**/
	public function has_cooked_amplitude_envelope_data():Bool;
	/**
		x.has_cooked_fft_data() -> bool
		Queries if the sound wave playing in this audio component has cooked FFT data, returns FALSE if none found.
		
		Returns:
		    bool:
	**/
	public function has_cooked_fft_data():Bool;
	/**
		(Array(AudioComponentParam)):  [Read-Write] Array of per-instance parameters for this AudioComponent.
	**/
	public var instance_parameters : Array<Dynamic>;
	/**
		x.is_playing() -> bool
		Returns TRUE if the targeted Audio Component’s sound is playing.
		Doesn't indicate if the sound is paused or fading in/out. Use GetPlayState() to get the full play state.
		
		Returns:
		    bool:
	**/
	public function is_playing():Bool;
	/**
		(bool):  [Read-Write] Whether or not this sound plays when the game is paused in the UI
	**/
	public var is_ui_sound : Bool;
	/**
		x.is_virtualized() -> bool
		Returns if the sound is virtualized.
		
		Returns:
		    bool:
	**/
	public function is_virtualized():Bool;
	/**
		(float):  [Read-Write] The frequency of the Lowpass Filter (in Hz) to apply to this voice. A frequency of 0.0 is the device sample rate and will bypass the filter.
	**/
	public var low_pass_filter_frequency : Float;
	/**
		(SoundModulationDefaultRoutingSettings):  [Read-Write] Modulation Routing
	**/
	public var modulation_routing : unreal.SoundModulationDefaultRoutingSettings;
	/**
		(OnAudioFinished):  [Read-Write] Called when we finish playing audio, either because it played to completion or because a Stop() call turned it off early
	**/
	public var on_audio_finished : unreal.OnAudioFinished;
	/**
		(OnAudioMultiEnvelopeValue):  [Read-Write] On Audio Multi Envelope Value
	**/
	public var on_audio_multi_envelope_value : unreal.OnAudioMultiEnvelopeValue;
	/**
		(OnAudioPlayStateChanged):  [Read-Write] This function returns the Targeted Audio Component’s current Play State.
		Playing, if the sound is currently playing.
		Stopped, if the sound is stopped.
		Paused, if the sound is currently playing, but paused.
		Fading In, if the sound is in the process of Fading In.
		Fading Out, if the sound is in the process of Fading Out.
	**/
	public var on_audio_play_state_changed : unreal.OnAudioPlayStateChanged;
	/**
		(OnAudioPlaybackPercent):  [Read-Write] Called as a sound plays on the audio component to allow BP to perform actions based on playback percentage.
		Computed as samples played divided by total samples, taking into account pitch.
		Not currently implemented on all platforms.
	**/
	public var on_audio_playback_percent : unreal.OnAudioPlaybackPercent;
	/**
		(OnAudioSingleEnvelopeValue):  [Read-Write] On Audio Single Envelope Value
	**/
	public var on_audio_single_envelope_value : unreal.OnAudioSingleEnvelopeValue;
	/**
		(OnAudioVirtualizationChanged):  [Read-Write] Called when virtualization state changes
	**/
	public var on_audio_virtualization_changed : unreal.OnAudioVirtualizationChanged;
	/**
		(bool):  [Read-Write] Allows defining attenuation settings directly on this audio component without using an attenuation settings asset.
	**/
	public var override_attenuation : Bool;
	/**
		(bool):  [Read-Write] Override Priority
	**/
	public var override_priority : Bool;
	/**
		(bool):  [Read-Write] Whether or not to override the sound's subtitle priority.
	**/
	public var override_subtitle_priority : Bool;
	/**
		(float):  [Read-Write] The upper bound to use when randomly determining a pitch multiplier
	**/
	public var pitch_modulation_max : Float;
	/**
		(float):  [Read-Write] The lower bound to use when randomly determining a pitch multiplier
	**/
	public var pitch_modulation_min : Float;
	/**
		(float):  [Read-Write] A pitch multiplier to apply to sounds generated by this component
	**/
	public var pitch_multiplier : Float;
	/**
		deprecated: 'pitch_multiplier_max' was renamed to 'pitch_modulation_max'.
	**/
	@:deprecated
	public var pitch_multiplier_max : Dynamic;
	/**
		deprecated: 'pitch_multiplier_min' was renamed to 'pitch_modulation_min'.
	**/
	@:deprecated
	public var pitch_multiplier_min : Dynamic;
	/**
		x.play(start_time=0.000000) -> None
		Begins playing the targeted Audio Component’s sound at the designated Start Time, seeking into a sound.
		
		Args:
		    start_time (float): The offset, in seconds, to begin reading the sound at
	**/
	public function play(start_time:Float = 0.000000):Void;
	/**
		x.play_quantized(world_context_object, clock_handle, quantization_boundary, delegate, start_time=0.000000, fade_in_duration=0.000000, fade_volume_level=1.000000, fade_curve=AudioFaderCurve.LINEAR) -> (clock_handle=QuartzClockHandle, quantization_boundary=QuartzQuantizationBoundary)
		Start a sound playing on an audio component on a given quantization boundary with the handle to an existing clock
		
		Args:
		    world_context_object (Object): 
		    clock_handle (QuartzClockHandle): 
		    quantization_boundary (QuartzQuantizationBoundary): 
		    delegate (OnQuartzCommandEventBP): 
		    start_time (float): 
		    fade_in_duration (float): 
		    fade_volume_level (float): 
		    fade_curve (AudioFaderCurve): 
		
		Returns:
		    tuple: 
		
		    clock_handle (QuartzClockHandle): 
		
		    quantization_boundary (QuartzQuantizationBoundary):
	**/
	public function play_quantized(world_context_object:unreal.Object, clock_handle:unreal.QuartzClockHandle, quantization_boundary:unreal.QuartzQuantizationBoundary, delegate:unreal.OnQuartzCommandEventBP, start_time:Float = 0.000000, fade_in_duration:Float = 0.000000, fade_volume_level:Float = 1.000000, ?fade_curve:unreal.AudioFaderCurve):python.Tuple<Dynamic>;
	/**
		(float):  [Read-Write] A priority value that is used for sounds that play on this component that scales against final output volume.
	**/
	public var priority : Float;
	/**
		x.set_audio_bus_send_post_effect(audio_bus, audio_bus_send_level) -> None
		Sets how much audio the sound should send to the given Audio Bus (POST Source Effects).
		if the Audio Bus Send doesn't already exist, it will be added to the overrides on the active sound.
		
		Args:
		    audio_bus (AudioBus): The Bus to send the signal to
		    audio_bus_send_level (float): The scalar used to alter the volume of the copied signal
	**/
	public function set_audio_bus_send_post_effect(audio_bus:unreal.AudioBus, audio_bus_send_level:Float):Void;
	/**
		x.set_audio_bus_send_pre_effect(audio_bus, audio_bus_send_level) -> None
		Sets how much audio the sound should send to the given Audio Bus (PRE Source Effects).
		if the Bus Send doesn't already exist, it will be added to the overrides on the active sound.
		
		Args:
		    audio_bus (AudioBus): The Bus to send the signal to
		    audio_bus_send_level (float): The scalar used to alter the volume of the copied signal
	**/
	public function set_audio_bus_send_pre_effect(audio_bus:unreal.AudioBus, audio_bus_send_level:Float):Void;
	/**
		x.set_bool_parameter(name, bool) -> None
		Allows the designer to set the Boolean Parameter on the SoundCue whose name matches the name indicated.
		
		Args:
		    name (Name): The name of the Boolean to set. It must match the name set in SoundCue's Branch Node
		    bool (bool): The value to set the Parameter to
	**/
	public function set_bool_parameter(name:unreal.Name, bool:Bool):Void;
	/**
		x.set_float_parameter(name, float) -> None
		Allows the designer to set the Float Parameter on the SoundCue whose name matches the name indicated.
		
		Args:
		    name (Name): The name of the Float to set. It must match the name set in SoundCue's Crossfade By Param or Continuous Modulator Node.
		    float (float): The value to set the Parameter to.
	**/
	public function set_float_parameter(name:unreal.Name, float:Float):Void;
	/**
		x.set_int_parameter(name, int) -> None
		Allows the designer to set the Integer Parameter on the SoundCue whose name matches the name indicated.
		
		Args:
		    name (Name): The name of the Integer to set. It must match the name set in SoundCue's Switch Node
		    int (int32): The value to set the Parameter to
	**/
	public function set_int_parameter(name:unreal.Name, int:Int):Void;
	/**
		x.set_low_pass_filter_enabled(low_pass_filter_enabled) -> None
		When set to TRUE, enables an additional Low Pass Filter Frequency to be calculated in with the
		sound instance’s LPF total, allowing designers to set filter settings for the targeted Audio Component’s
		sound instance.
		
		Args:
		    low_pass_filter_enabled (bool):
	**/
	public function set_low_pass_filter_enabled(low_pass_filter_enabled:Bool):Void;
	/**
		x.set_low_pass_filter_frequency(low_pass_filter_frequency) -> None
		Sets a cutoff frequency, in Hz, for the targeted Audio Component’s sound’s Low Pass Filter calculation.
		The lowest cutoff frequency from all of the sound instance’s possible LPF calculations wins.
		
		Args:
		    low_pass_filter_frequency (float):
	**/
	public function set_low_pass_filter_frequency(low_pass_filter_frequency:Float):Void;
	/**
		x.set_output_to_bus_only(output_to_bus_only) -> None
		Sets whether or not to output the audio to bus only.
		
		Args:
		    output_to_bus_only (bool):
	**/
	public function set_output_to_bus_only(output_to_bus_only:Bool):Void;
	/**
		x.set_paused(pause) -> None
		Pause an audio component playing its sound cue, issue any delegates if needed
		
		Args:
		    pause (bool):
	**/
	public function set_paused(pause:Bool):Void;
	/**
		x.set_pitch_multiplier(new_pitch_multiplier) -> None
		Set a new pitch multiplier
		
		Args:
		    new_pitch_multiplier (float):
	**/
	public function set_pitch_multiplier(new_pitch_multiplier:Float):Void;
	/**
		x.set_sound(new_sound) -> None
		Set what sound is played by this component
		
		Args:
		    new_sound (SoundBase):
	**/
	public function set_sound(new_sound:unreal.SoundBase):Void;
	/**
		x.set_source_bus_send_post_effect(sound_source_bus, source_bus_send_level) -> None
		Allows designers to target a specific Audio Component instance’s sound and set the send level (volume of sound copied)
		to the indicated Source Bus. If the Source Bus is not already part of the sound’s sends, the reference will be added to
		this instance’s Override sends. This particular send occurs after the Source Effect processing chain.
		
		Args:
		    sound_source_bus (SoundSourceBus): The Bus to send the signal to
		    source_bus_send_level (float): The scalar used to alter the volume of the copied signal
	**/
	public function set_source_bus_send_post_effect(sound_source_bus:unreal.SoundSourceBus, source_bus_send_level:Float):Void;
	/**
		x.set_source_bus_send_pre_effect(sound_source_bus, source_bus_send_level) -> None
		Allows designers to target a specific Audio Component instance’s sound and set the send level (volume of sound copied)
		to the indicated Source Bus. If the Source Bus is not already part of the sound’s sends, the reference will be added to
		this instance’s Override sends. This particular send occurs before the Source Effect processing chain.
		
		Args:
		    sound_source_bus (SoundSourceBus): The Bus to send the signal to.
		    source_bus_send_level (float): The scalar used to alter the volume of the copied signal.
	**/
	public function set_source_bus_send_pre_effect(sound_source_bus:unreal.SoundSourceBus, source_bus_send_level:Float):Void;
	/**
		x.set_submix_send(submix, send_level) -> None
		Allows designers to target a specific Audio Component instance’s sound set the send level (volume of sound copied) to the indicated Submix.
		
		Args:
		    submix (SoundSubmixBase): The Submix to send the signal to.
		    send_level (float): The scalar used to alter the volume of the copied signal.
	**/
	public function set_submix_send(submix:unreal.SoundSubmixBase, send_level:Float):Void;
	/**
		x.set_ui_sound(ui_sound) -> None
		Set whether sounds generated by this audio component should be considered UI sounds
		
		Args:
		    ui_sound (bool):
	**/
	public function set_ui_sound(ui_sound:Bool):Void;
	/**
		x.set_volume_multiplier(new_volume_multiplier) -> None
		Set a new volume multiplier
		
		Args:
		    new_volume_multiplier (float):
	**/
	public function set_volume_multiplier(new_volume_multiplier:Float):Void;
	/**
		x.set_wave_parameter(name, wave) -> None
		Allows the designer to set the Wave Parameter on the SoundCue whose name matches the name indicated.
		
		Args:
		    name (Name): The name of the Wave to set. It must match the name set in SoundCue's WaveParam Node
		    wave (SoundWave): The value to set the Parameter to
	**/
	public function set_wave_parameter(name:unreal.Name, wave:unreal.SoundWave):Void;
	/**
		(SoundBase):  [Read-Write] The sound to be played
	**/
	public var sound : unreal.SoundBase;
	/**
		(SoundEffectSourcePresetChain):  [Read-Write] The chain of Source Effects to apply to the sounds playing on the Audio Component
	**/
	public var source_effect_chain : unreal.SoundEffectSourcePresetChain;
	/**
		x.stop() -> None
		Stop an audio component's sound, issue any delegates if needed
	**/
	public function stop():Void;
	/**
		x.stop_delayed(delay_time) -> None
		Cues request to stop sound after the provided delay (in seconds), stopping immediately if delay is zero or negative
		
		Args:
		    delay_time (float):
	**/
	public function stop_delayed(delay_time:Float):Void;
	/**
		(float):  [Read-Write] Used by the subtitle manager to prioritize subtitles wave instances spawned by this component.
	**/
	public var subtitle_priority : Float;
	/**
		(bool):  [Read-Write] If true, subtitles in the sound data will be ignored.
	**/
	public var suppress_subtitles : Bool;
	/**
		(float):  [Read-Write] The upper bound to use when randomly determining a volume multiplier
	**/
	public var volume_modulation_max : Float;
	/**
		(float):  [Read-Write] The lower bound to use when randomly determining a volume multiplier
	**/
	public var volume_modulation_min : Float;
	/**
		(float):  [Read-Write] A volume multiplier to apply to sounds generated by this component
	**/
	public var volume_multiplier : Float;
	/**
		deprecated: 'volume_multiplier_max' was renamed to 'volume_modulation_max'.
	**/
	@:deprecated
	public var volume_multiplier_max : Dynamic;
	/**
		deprecated: 'volume_multiplier_min' was renamed to 'volume_modulation_min'.
	**/
	@:deprecated
	public var volume_multiplier_min : Dynamic;
}